import {
  Button,
  NavBar,
  Tabbar,
  TabbarItem,
  Empty,
  Image as VanImage,
  Lazyload,
  Icon,
  Cell,
  CellGroup,
  Dialog,
  Notify,
  NoticeBar,
  Form,
  Field,
  Tab,
  Tabs,
  Checkbox,
  Search,
  CheckboxGroup,
  Toast,
  Uploader,
  Card,
  Grid,
  ImagePreview,
  SwipeItem,
  Swipe,
  GridItem,
  SidebarItem,
  Sidebar,
  Col,
  Row,
  List,
  ActionBarIcon,
  ActionBar,
  ActionBarButton,
  ShareSheet,
  AddressList,
  AddressEdit,
  SubmitBar,
  ContactCard,
  Skeleton,
  Switch,
  Tag,
  Stepper,
  ActionSheet
} from 'vant'

Toast.setDefaultOptions('loading', { forbidClick: true, duration: 0 })
Toast.allowMultiple()

export default function (app) {
  app
      .use(Row)
      .use(Col)
      .use(Sidebar)
      .use(SidebarItem)
    .use(Button)
    .use(NavBar)
    .use(Tabbar)
    .use(TabbarItem)
    .use(Empty)
    .use(VanImage)
    .use(Lazyload)
    .use(Icon)
    .use(Cell)
    .use(CellGroup)
    .use(Dialog)
    .use(Notify)
    .use(Form)
    .use(Field)
    .use(Tab)
    .use(Tabs)
    .use(Checkbox)
    .use(CheckboxGroup)
    .use(Toast)
    .use(Uploader)
    .use(ImagePreview)
    .use(Card)
    .use(Swipe)
    .use(SwipeItem)
      .use(Search)
      .use(NoticeBar)
      .use(Grid)
      .use(GridItem)
      .use(List)
      .use(ActionBarIcon)
      .use(ActionBar)
      .use(ActionBarButton)
      .use(ShareSheet)
      .use(AddressList)
      .use(AddressEdit)
      .use(SubmitBar)
      .use(ContactCard)
      .use(Skeleton)
      .use(Switch)
      .use(Tag)
      .use(Stepper)
      .use(ActionSheet)
}
